apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${deploy_name}
  namespace: ${namespace}
spec:
  serviceAccountName: helm-controller
  values:
%{ if is_debug_mode ~}
    global:
      logLevel: 1
%{ endif ~}