apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ${gitops_apps_repo_url}/apps/${deploy_name}?ref=${gitops_apps_repo_branch}
%{ if enable_azure_storage_external_secret ~}
  - service-account.yaml
  - external-secret.yaml
  - secret-store.yaml
%{ endif ~}
patches:
  - path: patch.yaml
    target:
      kind: HelmRelease
      name: velero
      namespace: velero
