apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: velero-ssm
  namespace: velero
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: ssm-secrets
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: velero-1password
  namespace: velero
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.1password-connect.svc.cluster.local:8080
      vaults:
        CloudEng-General: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: velero-1password-token
            key: token