kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeControllerManager:
  enabled: false

kubeProxy:
  enabled: false

nodeExporter:
  enabled: false

kubeStateMetrics:
  enabled: false

kubelet:
  enabled: false

coreDns:
  enabled: false


kubeApiServer:
  enabled: false