prometheus-node-exporter:
  resources:
    requests:
      cpu: 20m
      memory: 50Mi
  priorityClassName: ${prometheus_node_exporter_priorityclass}
  prometheus:
    monitor:
      enabled: true
  rbac:
    pspEnabled: true
