apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-blackbox-exporter
  namespace: monitoring
spec:
  chart:
    spec:
      version: ${chart_version}
  values:
    serviceMonitor:
      enabled: true
      targets:
        %{~ for target in monitoring_targets ~}
        - name: ${target.name}
          url: ${target.url}
          module: ${target.module}
        %{~ endfor ~}
