apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-blackbox-exporter
  namespace: ${namespace}
spec:
  serviceAccountName: helm-controller
  chart:
    spec:
      version: "${helm_chart_version}"
  values:
    deployment:
      replicas: ${replicas}
    serviceMonitor:
      enabled: true
      targets:
        %{~ for target in monitoring_targets ~}
        - name: ${target.name}
          url: ${target.url}
          module: ${target.module}
        %{~ endfor ~}
