apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: ${deploy_name}
  namespace: external-dns
spec:
  endpoints:
  %{~ for record in dns_records_anon ~}
    - dnsName: ${record}
      recordTTL: 300
      recordType: CNAME
      targets:
      - ${target_anon}
  %{~ endfor ~}
  %{~ for record in dns_records_auth ~}
    - dnsName: ${record}
      recordTTL: 300
      recordType: CNAME
      targets:
      - ${target_auth}
  %{~ endfor ~}
