apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --no-cross-namespace-refs=true
    target:
      kind: Deployment
      # trunk-ignore(yamllint/quoted-strings)
      name: "(kustomize-controller|notification-controller|image-reflector-controller|image-automation-controller)"
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --default-service-account=default
    target:
      kind: Deployment
      # trunk-ignore(yamllint/quoted-strings)
      name: "(kustomize-controller|helm-controller)"
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --concurrent=40
    target:
      kind: Deployment
      # trunk-ignore(yamllint/quoted-strings)
      name: "helm-controller"
  - patch: |
      - op: add
        path: /spec/serviceAccountName
        value: kustomize-controller
    target:
      kind: Kustomization
      # trunk-ignore(yamllint/quoted-strings)
      name: "flux-system"
%{ if src_ctrl_arn != "" }
  - patch: |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: source-controller
        annotations:
          eks.amazonaws.com/role-arn: "${src_ctrl_arn}"
          eks.amazonaws.com/sts-regional-endpoints: "true"
    target:
      kind: ServiceAccount
      name: source-controller
%{ endif ~}
