---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: platform-apps-git
  namespace: flux-system
spec:
  interval: 1m0s
%{ if gitops_apps_repo_tag != "" ~}
  ref:
    tag: ${gitops_apps_repo_tag}
%{ else ~}
  ref:
    branch: ${gitops_apps_repo_ref}
%{ endif ~}
  url: ${gitops_apps_repo_url}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-apps-sources
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 1m0s
  dependsOn:
    - name: flux-system
  sourceRef:
    kind: GitRepository
    name: platform-apps-git
  path: ./sources
  prune: ${prune}
