resource "aws_iam_policy" "preventive" {
  name = "PreventivePolicy"

  policy = jsonencode({
    Version = "2012-10-17",
    Statement = [
      {
        Sid       = "DenyExpensiveEC2",
        Effect    = "Deny",
        Action    = ["ec2:RunInstances"],
        Resource  = ["arn:aws:ec2:*:*:instance/*"],
        Condition = {
          StringLike = {
            "ec2:InstanceType" = [
              "i*",
              "p*",
              "x*",
              "*.1*",
              "*.8*",
              "*.24*",
              "*.metal",
            ],
          },
        },
      },
      {
        Sid       = "DenyVPNCreation",
        Effect    = "Deny",
        Action    = [
          "ec2:AttachVpnGateway",
          "ec2:CreateVpnConnection",
          "ec2:CreateVpnConnectionRoute",
          "ec2:CreateVpnGateway",
          "ec2:DeleteVpnConnection",
          "ec2:DeleteVpnConnectionRoute",
          "ec2:DeleteVpnGateway",
          "ec2:DetachVpnGateway",
        ],
        Resource  = ["*"],
      },
      {
        Sid       = "DenyDisablingGuardDuty",
        Effect    = "Deny",
        Action    = [
          "guardduty:AcceptInvitation",
          "guardduty:ArchiveFindings",
          "guardduty:CreateDetector",
          "guardduty:CreateFilter",
          "guardduty:CreateIPSet",
          "guardduty:CreateMembers",
          "guardduty:CreatePublishingDestination",
          "guardduty:CreateSampleFindings",
          "guardduty:CreateThreatIntelSet",
          "guardduty:DeclineInvitations",
          "guardduty:DeleteDetector",
          "guardduty:DeleteFilter",
          "guardduty:DeleteInvitations",
          "guardduty:DeleteIPSet",
          "guardduty:DeleteMembers",
          "guardduty:DeletePublishingDestination",
          "guardduty:DeleteThreatIntelSet",
          "guardduty:DisassociateFromMasterAccount",
          "guardduty:DisassociateMembers",
          "guardduty:InviteMembers",
          "guardduty:StartMonitoringMembers",
          "guardduty:StopMonitoringMembers",
          "guardduty:TagResource",
          "guardduty:UnarchiveFindings",
          "guardduty:UntagResource",
          "guardduty:UpdateDetector",
          "guardduty:UpdateFilter",
          "guardduty:UpdateFindingsFeedback",
          "guardduty:UpdateIPSet",
          "guardduty:UpdatePublishingDestination",
          "guardduty:UpdateThreatIntelSet",
        ],
        Resource  = "*",
      },
      {
        Sid       = "DenyLeavingOfOrganisation",
        Effect    = "Deny",
        Action    = "organizations:LeaveOrganization",
        Resource  = "*",
      },
      {
        Sid       = "DenyDisablingSecurityHub",
        Effect    = "Deny",
        Action    = [
          "securityhub:DeleteInvitations",
          "securityhub:DisableSecurityHub",
          "securityhub:DisassociateFromMasterAccount",
          "securityhub:DeleteMembers",
          "securityhub:DisassociateMembers",
          "securityhub:UpdateStandardsControl",
          "securityhub:BatchUpdateStandardsControlAssociations",
        ],
        Resource  = "*",
      },
      {
        Sid       = "DenyDisablingMacie",
        Effect    = "Deny",
        Action    = [
          "macie2:DisassociateFromMasterAccount",
          "macie2:DisableOrganizationAdminAccount",
          "macie2:DisableMacie",
          "macie2:DeleteMember",
        ],
        Resource  = "*",
      },
    ],
  })
}
