apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${deploy_name}
  namespace: ${namespace}
spec:
  serviceAccountName: helm-controller
  chart:
    spec:
      version: "${chart_version}"
  values:
%{ if length(affinity) > 0 ~}
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
%{ for a in affinity ~}
              - key: ${a.key}
                operator: ${a.operator}
                values:
%{ for v in a.values ~}
                  - ${ v }
%{ endfor ~}
%{ endfor ~}
%{ endif ~}
%{ if length(tolerations) > 0 ~}
    tolerations:
%{ for t in tolerations ~}
      - key: ${t.key}
        operator: ${t.operator}
%{ if t.value != null ~}
        value: ${t.value}
%{ endif ~}
        effect: ${t.effect}
%{ endfor ~}
%{ endif ~}
