apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ${gitops_apps_repo_url}/apps/${deploy_name}?ref=${gitops_apps_repo_branch}
patches:
  - path: patch.yaml
    target:
      kind: HelmRelease
      name: druid-operator
      namespace: druid-system
