apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${deploy_name}
  namespace: druid-system
spec:
  serviceAccountName: helm-controller
  chart:
    spec:
      version: "${chart_version}"
  values:
    env:
      WATCH_NAMESPACE: "${watch_namespace}"
    resources:
      limits:
        memory: ${resources_requests_memory}
      requests:
        cpu: ${resources_requests_cpu}
        memory: ${resources_requests_memory}
