image:
  repository: ${atlantis_image}
  tag: ${atlantis_image_tag}
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: 1536Mi
    cpu: 100m
  limits:
    memory: 1536Mi
    cpu: null

orgWhitelist: ${github_repos}
logLevel: "info"

disableApply: true
disableApplyAll: true

volumeClaim:
  storageClassName: ${storage_class}

github:
  user: ${github_username}

extraArgs:
  - --disable-autoplan

ingress:
  host: ${atlantis_ingress}
  annotations:
    kubernetes.io/ingress.class: ${ingress_class}
    traefik.ingress.kubernetes.io/auth-type: ${ingress_auth_type}
    traefik.ingress.kubernetes.io/auth-secret: ${auth_secret_name}

service:
  type: ClusterIP

repoConfig: |
  ---
  repos:
  - id: "/.*/"
    workflow: terragrunt
    allowed_overrides: [workflow]
  workflows:
    terragrunt:
      plan:
        steps:
        - run: env | awk -F'=' '{print $1"="substr($2, 1, 3)"***"}'
        - run: terragrunt run-all plan -no-color --terragrunt-non-interactive -input=false
      apply:
        steps:
        - run: exit 1
    eks-pipeline:
      plan:
        steps:
        - run: terragrunt run-all plan -no-color --terragrunt-non-interactive -input=false
      apply:
        steps:
        - run: exit 1
