image:
  repository: ${atlantis_image}
  tag: ${atlantis_image_tag}
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: ${resources_requests_memory}
    cpu: ${resources_requests_cpu}
  limits:
    memory: ${resources_limits_memory}
    cpu: ${resources_limits_cpu}

orgAllowlist: ${github_repos}
logLevel: "info"

disableApply: true
disableApplyAll: true

volumeClaim:
  dataStorage: ${data_storage}
  storageClassName: ${storage_class}

github:
  user: ${github_username}

extraArgs:
  - --parallel-pool-size=${parallel_pool_size}

ingress:
  host: ${atlantis_ingress}
  annotations:
    kubernetes.io/ingress.class: ${ingress_class}
    traefik.ingress.kubernetes.io/auth-type: ${ingress_auth_type}
    traefik.ingress.kubernetes.io/auth-secret: ${auth_secret_name}

service:
  type: ClusterIP

repoConfig: |
  ---
  repos:
  - id: "/.*/"
    allowed_overrides: [workflow]
    allow_custom_workflows: true

%{ if add_secret_volumes ~}
extraVolumes:
  - name: kubeconfigs
    secret:
      secretName: kubeconfigs
      defaultMode: 0644

extraVolumeMounts:
  - name: kubeconfigs
    readOnly: true
    mountPath: "/kubeconfigs"
%{ endif ~}


statefulSet:
  securityContext:
    runAsUser: 200