apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${deploy_name}-config
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 1m0s
  dependsOn:
    - name: ${deploy_name}-controller
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./${config_repo_path}"
  prune: ${prune}
