apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${deploy_name}-controller
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: ${deploy_name}-crd
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./${controller_repo_path}"
  prune: ${prune}
