apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${deploy_name}
  namespace: ${namespace}
spec:
  serviceAccountName: helm-controller
  chart:
    spec:
      version: "${chart_version}"
  values:
    resources:
      limits:
        cpu: ${resources_limits_cpu}
        memory: ${resources_limits_memory}
      requests:
        cpu: ${resources_requests_cpu}
        memory: ${resources_requests_memory}
    trivy:
      githubToken: ${github_token}
      resources:
        limits:
          cpu: ${resources_limits_cpu}
          memory: ${resources_limits_memory}
        requests:
          cpu: ${resources_requests_cpu}
          memory: ${resources_requests_memory}
