apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${deploy_name}
  namespace: "trivy-system"
spec:
  chart:
    spec:
      version: "${chart_version}"
  values:
    resources:
      limits:
        memory: ${resources_requests_memory}
      requests:
        cpu: ${resources_requests_cpu}
        memory: ${resources_requests_memory}
    trivy:
      githubToken: ${github_token}
      resources:
        limits:
          memory: ${scan_resources_requests_memory}
        requests:
          cpu: ${scan_resources_requests_cpu}
          memory: ${scan_resources_requests_memory}
