apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${app_install_name}-config
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: ${app_install_name}-helm
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./${config_repo_path}"
  prune: ${prune}
