apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: ${app_install_name}-helm
    namespace: flux-system
spec:
    interval: 1m0s
    dependsOn:
       - name: platform-apps-sources
    sourceRef:
        kind: GitRepository
        name: flux-system
    path: "./${helm_repo_path}"
    prune: ${prune}

