apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${deploy_name}
  namespace: ${namespace}
spec:
  serviceAccountName: helm-controller
  chart:
    spec:
      version: ${helm_chart_version}
  values:
    ports:
      web:
        nodePort: ${http_nodeport}
      traefik:
        nodePort: ${admin_nodeport}
    additionalArguments:
  %{~ for arg in additional_args ~}
      - ${arg}
  %{~ endfor ~}
    deployment:
      replicas: ${replicas}
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`${dashboard_ingress_host}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
        entryPoints: [traefik, web]
