apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${deploy_name}
  namespace: ${namespace}
spec:
  chart:
    spec:
      version: ${helm_chart_version}
  values:
    ports:
      web:
        nodePort: ${http_nodeport}
      traefik:
        nodePort: ${admin_nodeport}
    additionalArguments: ${additional_args}
    deployment:
      replicas: ${replicas}
