---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ssm-secrets
  namespace: flux-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${account_id}:role/${role_name}
    eks.amazonaws.com/sts-regional-endpoints: "true"
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: shared-manifests-git
  namespace: flux-system
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: ssm-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shared-manifests-git
  namespace: flux-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: shared-manifests-git
  target:
    name: shared-manifests-git
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: /github/username/shared-manifests
    - secretKey: password
      remoteRef:
        key: /github/token/shared-manifests
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: shared-manifests-git
  namespace: flux-system
spec:
  interval: 1m0s
  secretRef:
    name: shared-manifests-git
  ref:
    branch: ${shared_manifests_repo_branch}
  url: ${shared_manifests_repo_url}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: shared-manifests
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: flux-system
  sourceRef:
    kind: GitRepository
    name: shared-manifests-git
  path: ./infrastructure/${overlay_folder}
  prune: ${prune}
