---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: shared-manifests-git
  namespace: flux-system
spec:
  interval: 1m0s
  secretRef:
    name: shared-manifests-git
  ref:
    branch: ${shared_manifests_repo_branch}
  url: ${shared_manifests_repo_url}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: shared-manifests-druid-operator
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: flux-system
    - name: platform-apps-sources
    - name: platform-apps-external-secrets-helm
  sourceRef:
    kind: GitRepository
    name: shared-manifests-git
  path: ./infrastructure/${overlay_folder}/druid-operator
  prune: ${prune}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: shared-manifests-tiny-cluster
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: shared-manifests-druid-operator
  sourceRef:
    kind: GitRepository
    name: shared-manifests-git
  path: ./infrastructure/${overlay_folder}/tiny-cluster
  prune: ${prune}
