apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: ${role_arn}
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
%{ for arn in capability_access_arns ~}
    - rolearn: ${arn}
      username: aws:capabilityaccess
      groups:
        - system:masters
%{ endfor ~}
