apiVersion: v1
clusters:
- cluster:
    server: ${endpoint}
    certificate-authority-data: ${ca}
  name: ${cluster_name}
contexts:
- context:
    cluster: ${cluster_name}
    user: ${cluster_name}-saml
  name: ${cluster_name}-saml
current-context: ${cluster_name}-saml
kind: Config
preferences: {}
users:
- name: ${cluster_name}-saml
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws
      args:
        - "eks"
        - "get-token"
        - "--cluster-name"
        - "${cluster_name}"
      env:
        - name: AWS_PROFILE
          value: "saml"