apiVersion: v1
clusters:
- cluster:
    server: ${endpoint}
    certificate-authority-data: ${ca}
  name: ${cluster_name}
contexts:
- context:
    cluster: ${cluster_name}
    user: ${cluster_name}-token
  name: ${cluster_name}-token
current-context: ${cluster_name}-token
kind: Config
preferences: {}
users:
- name: ${cluster_name}-token
  user:
    token: ${token}