---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-reconciler-${deploy_name}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: helm-controller
    namespace: ${namespace}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${app_install_name}-helm
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./${helm_repo_path}"
  prune: ${prune}
  postBuild:
    substitute:
      flux_aws_lb_controller_role_arn: ${role_arn}
      flux_cluster_name: ${cluster}
      flux_aws_region: ${region}
