apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${deploy_name}
  namespace: ${namespace}
spec:
  values:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: ${role_arn}
    region: ${region}
    clusterName: ${cluster}
