---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${app_install_name}-policies
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 1m0s
  dependsOn:
    - name: ${app_install_name}-helm
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./${policies_repo_path}"
  prune: true
  wait: true
  timeout: 5m
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kyverno-admission-controller
      namespace: kyverno
    - apiVersion: v1
      kind: Service
      name: kyverno-svc
      namespace: kyverno
