---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${app_install_name}-policy-reporter-helm
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 1m0s
  dependsOn:
    - name: ${app_install_name}-helm
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./${reporter_repo_path}"
  prune: true
  wait: true
  timeout: 5m
