apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubeconfigs
  namespace: atlantis
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: atlantis-ssm
  target:
    name: kubeconfigs
  data:
    - secretKey: ${cluster_name}-kubeconfig-deploy-user.config
      remoteRef:
        key: /eks/${cluster_name}/kubeconfig-deploy-user
