apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: atlantis
  namespace: atlantis
spec:
  values:
    basicAuth:
      username: atlantis
      password: ${basic_auth_password}
    github:
      secret: ${github_secret}
      token: ${github_token}
      user: ${github_username}
    orgAllowlist: ${org_allowlist}
