name: Auto release on merge

on:
  push:
    branches: ["master", "main"]
    paths-ignore:
      - ".github/**"
      - ".trunk/**"
      - "**/*.md"
      - ".gitignore"
      - ".pre-commit-config.yaml"
      - "LICENSE"
      - "renovate.json"
      - "test/**"
      - "src/**"
      - "mise.toml"

jobs:
  auto-release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
          tag_prefix: ""
