name: Auto release on merge

on:
  push:
    branches: ["master"]
    paths-ignore:
      - ".github/**"
      - "**/*.md"
      - ".gitignore"
      - ".pre-commit-config.yaml"
      - "LICENSE"
      - "renovate.json"
      - "test/**"
      - "src/**"
      - "mise.toml"

jobs:
  auto-release:
    uses: dfds/shared-workflows/.github/workflows/automation-auto-release.yml@v2.0.1
