name: Block on-hold PRs

on:
  pull_request:
    branches: [ master, main ]
    types: [ opened, labeled, unlabeled, synchronize ]

jobs:
  shared:
    uses: dfds/shared-workflows/.github/workflows/automation-on-hold-prs.yml@master
