name: "Pull Request Labeler"

on:
  pull_request_target:
    types: ["opened"]
    branches: ["master", "main"]

jobs:
  labeler:
    if: github.event.pull_request.user.login == 'devex-sa'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Apply labels
        id: label-the-PR
        uses: actions/labeler@v5
        with:
          configuration-path: ".github/pr-labels.yml"
      
      # Tried using a matrix for this but that floaded the PR checks
      - name: Remove patch release
        if: |
          contains(steps.label-the-PR.outputs.all-labels, 'norelease') &&
          contains(steps.label-the-PR.outputs.all-labels, 'release:patch')
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: 'release:patch'
            })
      - name: Remove minor release
        if: |
          contains(steps.label-the-PR.outputs.all-labels, 'norelease') &&
          contains(steps.label-the-PR.outputs.all-labels, 'release:minor')
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: 'release:minor'
            })
      - name: Remove major release
        if: |
          contains(steps.label-the-PR.outputs.all-labels, 'norelease') &&
          contains(steps.label-the-PR.outputs.all-labels, 'release:major')
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: 'release:major'
            })
