name: Gitleaks

on:
  pull_request:
    branches: ["master"]

jobs:
  shared:
    uses: dfds/shared-workflows/.github/workflows/security-gitleaks.yml@v2.0.1
    secrets: inherit # pragma: allowlist secret
