name: Gitleaks

on:
  pull_request:
    branches: ["master"]

jobs:
  shared:
    uses: dfds/shared-workflows/.github/workflows/security-gitleaks.yml@2.0.4
    secrets: inherit # pragma: allowlist secret
